apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellp
  namespace: lasample
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: linuxacademycontent/getops:hellov1.1
